### PR TITLE
attempt to be next-gen on travis-ci

### PR DESCRIPTION
**Pull request by gretel**

### CODE REVIEW

**Comment by bucaran** [comment]
osx?

**Comment by gretel** [comment]
http://docs.travis-ci.com/user/multi-os/
> We are at capacity with Mac workers in both .org and .com environments. Consequently, we are not accepting requests for the multi-OS feature at this time. As more capacity is added, we will resume accepting requests.

**Comment by bucaran** [comment]
Why did you comment out `osx`, how are we going to run tests on OSX?

**Comment by gretel** [comment]
it would be good if you could read what i posted twice on gitter and now again here in the PR. there are no osx build happening currently

**Comment by bucaran** [comment]
Thanks. But if there is not osx support then we should not migrate to the new infra, don't you think?

**Comment by gretel** [comment]
that is unrelated. what changed is the containment (i.e. they using docker now) not the support in regards to vm. besides, it's the only !linux platform currently supported, and that will have to be treated differently, anyway

**Comment by bucaran** [comment]
Did Travis change its infra in a way that makes impossible to test software in OSX?

**Comment by gretel** [comment]
please, just read what the documentation reads. i really can't say anything else:
http://docs.travis-ci.com/user/multi-os/

**Comment by bucaran** [comment]
> We are not currently accepting multi-OS requests

This is breaking news then.

But

> This is a beta feature

So why care?

**Comment by gretel** [comment]
it is still unrelated.
i do wonder, why require `sudo` for testing, while no `osx` build occur, and we using `homebrew` don't use `sudo` at all to get `wahoo` running.
furthermore, i don't feel like waiting for travis i a good pattern. it travis takes long ci is no good, i'd say.

**Comment by gretel** [comment]
17 sec is fine for me :)

**Comment by bucaran** [comment]
Nice!

Is there any way we could test `bootstrap.sh` features instead of getting fish via apt?

**Comment by bucaran** [comment]
when will osx be supported again?

**Comment by gretel** [comment]
guess when people made contributions and stuff :moneybag:

**Comment by bucaran** [comment]
I still don't understand this.

What is the problem, travis seems to be running OSX?

**Comment by bucaran** [comment]
Does travis support OSX?

**Comment by gretel** [comment]
@bucaran with all due resepct, bit it's the _fourth_ time i am pointing you to the documentation:
http://docs.travis-ci.com/user/multi-os/
_PLEAE_ have a read. i really can't answer your question regardless of how many times you repeat to.

**Comment by bucaran** [comment]
:+1:

**Comment by gretel** [comment]
cheers :cherries:

**Comment by bucaran** [comment]
:video_game:

**Comment by gretel** [comment]
i'll track travis in terms of multi-os support and will enjoy integrating this for our case :performing_arts:

**Pull request merged**
